### ISSUE TITLE
Domain Adapter Training

### ISSUE THREAD

**Issue by DopamineLcy** [Amano-Aki/Mixture-of-Domain-Adapters#3]
感谢您的出色工作和分享的代码！
有个问题想请教您：不同Domain的Domain Adapter在stage1是单独训练，在stage2再合到网络中吗？
希望能到知道更多关于多个Domain Adapter的训练方式细节。
谢谢！

**Comment by shizhediao** [comment]
Hi,
是的，不同Domain的Domain Adapter在stage1是单独训练，在stage2再合到网络中的。

-----

Hi,
Yes, the Domain Adapter for different Domains is trained separately in stage1, and then integrated into the network in stage2.

**Comment by DopamineLcy** [comment]
Thank you for your quick response!
